// Copyright 2022-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= OpenGL Shading Language Documentation

include::{config}/headerattribs.adoc[]

include::{config}/attribs.adoc[]


== About

This site includes the {slname}, Version {revnumber} specification.


== Navigation

The site is organized in "`components`" (Antora terminology for
specifications and other documents), each containing many "`pages`" (Antora
terminology for a chapter of a specification, or other distinct piece of
content for other components).

The left navigation sidebar links to pages in the current component.

The right navigation sidebar links to sections in the current page.

The bottom-left button switches between components.

The top navigation bar contains a text searchbox.
If the "`In this component`" box is checked, search will be restricted to
the current component.
Otherwise, all components of the site are searched.


== Site Information

link:https://docs.vulkan.org/[This site] is generated using the
link:https://docs.antora.org/[Antora] static site generator.

If you need to report a problem or build the site yourself, start with the
link:https://github.com/KhronosGroup/Vulkan-Site/[Vulkan-Site] repository on
GitHub.
